/*
 * Van Tracker Appside
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	"log"
	"net/http"

	sw "github.com/thatguycalledrob/gps-tracking/gps-mobile-app/cloud-app-server/go"
)

var client *firestore.Client

func main() {
	log.Printf("Server started")

	client = sw.setupFirestore()
	defer client.Close()

	router := sw.NewRouter()

	log.Fatal(http.ListenAndServe(":8080", router))
}
