/*
 * Van Tracker Appside
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	"fmt"
	"log"
	"net/http"
	"os"

	sw "github.com/thatguycalledrob/gps-tracking/gps-mobile-app/cloud-app-server/go"
)

func getPort() string {
	p := os.Getenv("PORT")
	if p == "" {
		p = "8080"
	}
	return p
}

func main() {
	log.Printf("Server started")

	client := sw.SetupFirestore()
	defer client.Close()

	router := sw.NewRouter()

	port := getPort()
	log.Fatal(http.ListenAndServe(fmt.Sprintf(":%s", port), router))
}
