/*
 * Van Tracker Appside
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	jsoniter "github.com/json-iterator/go"
	"log"
	"net/http"
)

var json = jsoniter.ConfigCompatibleWithStandardLibrary

func CurrentLocation(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")

	vals := GetLatestCoord()
	j, err := json.Marshal(&vals)
	if err != nil {
		log.Fatalf("Error marshelling %+v", vals)
	}
	w.Write(j)

	w.WriteHeader(http.StatusOK)
}

func QueryHistory(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
}

func RetriveParkingSpots(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
}
