/*
 * Van Tracker Appside
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Query struct {

	FromDate int64 `json:"fromDate"`

	ToDate int64 `json:"toDate"`

	Algorithm string `json:"algorithm"`
}
