/*
 * Van Tracker Appside
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Coordinate struct {

	Time int64 `json:"time,omitempty"`

	Sats float32 `json:"sats,omitempty"`

	Lat float32 `json:"lat"`

	Long float32 `json:"long"`

	Alt float32 `json:"alt"`

	Order int32 `json:"order"`

	Count int32 `json:"count,omitempty"`
}
