/*
 * Van Tracker Appside
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/app/v1/",
		Index,
	},

	Route{
		"CurrentLocation",
		strings.ToUpper("Get"),
		"/app/v1/current-location",
		CurrentLocation,
	},

	Route{
		"QueryHistory",
		strings.ToUpper("Post"),
		"/app/v1/history-query",
		QueryHistory,
	},

	Route{
		"RetriveParkingSpots",
		strings.ToUpper("Get"),
		"/app/v1/parking-spots",
		RetriveParkingSpots,
	},
}
